[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3

[pis]
pi-01.lan
pi-02.lan
pi-03.lan
pi-04.lan
pi-05.lan
pi-06.lan
pi-07.lan
pi-08.lan
pi-09.lan
pi-10.lan

[k3s_master]
pi-03.lan

[k3s_workers]
pi-01.lan
pi-02.lan
pi-04.lan
pi-05.lan
pi-06.lan
pi-07.lan
pi-08.lan
pi-09.lan
pi-10.lan
